# Generated by Django 3.1.2 on 2020-10-25 16:01

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='price',
            field=models.FloatField(default=0, validators=[main.validators.budget_validator]),
        ),
    ]
