# Generated by Django 3.1.2 on 2020-10-25 20:24

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201025_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='price',
            field=models.FloatField(default=0, validators=[main.validators.budget_validator, main.validators.availability_validator]),
        ),
    ]
